### ISSUE TITLE
Access by identifier

### ISSUE THREAD

**Issue by pelord** [ECCC-MSC/Wateroffice#1]
I think the provided URL do not represent the title of the section
[
https://github.com/ECCC-MSC/Wateroffice/blob/master/docs/msc-geomet-wfs3-api-howto-en.md#access-by-identifier](
https://github.com/ECCC-MSC/Wateroffice/blob/master/docs/msc-geomet-wfs3-api-howto-en.md#access-by-identifier)

**Comment by pelord** [comment]
It's look like the filtering component is not parsed by the server..

[https://geo.weather.gc.ca/geomet/features/collections/hydrometric-daily-mean/items?f=csv&limit=500&startindex=0&IDENTIFIER=08NE044.1939-06-07](https://geo.weather.gc.ca/geomet/features/collections/hydrometric-daily-mean/items?f=csv&limit=500&startindex=0&IDENTIFIER=08NE044.1939-06-07)

I've used the https://geo.weather.gc.ca/geomet/features/api to build the url....

**Comment by pelord** [comment]
@tomkralidis  Some update about this issue?

**Comment by tomkralidis** [comment]
@pelord the docs have been updated for this service (access by identifier).  Our next release will fix the property filtering.  Note that normative docs are at https://eccc-msc.github.io/open-data

**Comment by pelord** [comment]
👍
